config/routes.rb
Mblog::Application.routes.draw do
  
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  resources :categories

  resources :posts do
  	resources :comments
  end
  
  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  #devise_for :users
  resources :users 

  #match 'auth/facebook/callback' => 'sessions#create',:as => 'login'
  #match 'auth/linkedin/callback' => 'sessions#create',:as => 'login'
  #match 'logout' => 'sessions#destroy'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :body, :created_at, :post_id, :user_id, :publish_date
  validates_presence_of :body, :post_id, :user_id, :publish_date

  #MOD KIMADA 4/13/2013
  belongs_to :post

  def self.curr_date
  	Time.now.strftime("%d/%m/%Y %H:%M")
  end

  def self.find_user(user_id) 
  	@user = User.find(user_id)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :authenticate_user!
  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @comments }
    end
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    @comment = Comment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/new
  # GET /comments/new.json
  def new
    @comment = Comment.new
    @post = Post.find(params[:post_id]) # MOD KIMADA 4/11/2013

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/1/edit
  def edit
    @comment = Comment.find(params[:id])
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(params[:comment])

    respond_to do |format|
      if @comment.save
        format.html { redirect_to post_path(params[:post_id]), notice: 'Comment was successfully created.' }
        format.json { render json: @comment, status: :created, location: @comment }
      else
        # MOD KIMADA 4/13/2013
        # format.html { render action: "new" }
        format.html { redirect_to new_post_comment_path(params[:post_id]), notice: 'Comment body is blank. Please enter something.' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /comments/1
  # PUT /comments/1.json
  def update
    @comment = Comment.find(params[:id])

    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    respond_to do |format|
      # MOD KIMADA 4/14/2013 Change from comments_url to post_path...
      format.html { redirect_to post_path(params[:post_id]) }
      format.json { head :no_content }
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= simple_form_for([@post, @comment]) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :body %>
    <%# MOD KIMADA 4/13/2013 Hidden Fields %>
    <%= f.hidden_field :post_id, :value => @post.id %>
    <%= f.hidden_field :user_id, :value => current_user.id %>
    <%= f.hidden_field :publish_date, :value => Comment.curr_date %> 
  </div>

  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                post_path(:id => @post.id), :class => 'btn' %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', post_comment_path %>

app/views/comments/index.html.erb
<h1>Comments</h1>

<table>
  <tr>
    <th>Body</th>
    <th>Post</th>
    <th>User</th>
    <th>Created at</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @comments.each do |comment| %>
  <tr>
    <td><%= comment.body %></td>
    <td><%= comment.post_id %></td>
    <td><%= comment.user_id %></td>
    <td><%= comment.publish_date %></td>
    <td><%= link_to 'Show', comment %></td>
    <td><%= link_to 'Edit', edit_post_comment_path(comment) %></td>
    <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Comment', new_post_comment_path, :post_id => @comment.post_id %>

app/views/comments/new.html.erb
<h1>New Comment for <%=@post.title %> </h1>

<%= render 'form' %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Body:</b>
  <%= @comment.body %>
</p>

<p>
  <b>Post:</b>
  <%= @comment.post_id %>
</p>

<p>
  <b>User:</b>
  <%= @comment.user_id %>
</p>

<p>
  <b>Published at:</b>
  <%= @comment.publish_date %>
</p>


<%= link_to 'Edit', edit_post_comment_path(@comment) %> |
<%#%= link_to 'Back', post_comments_path %>