config/routes.rb
Mblog::Application.routes.draw do
  
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  resources :categories

  resources :posts do
  	resources :comments
  end
  
  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  #devise_for :users
  resources :users 

  #match 'auth/facebook/callback' => 'sessions#create',:as => 'login'
  #match 'auth/linkedin/callback' => 'sessions#create',:as => 'login'
  #match 'logout' => 'sessions#destroy'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	# MOD KIMADA 5/1/2013
	include HomeHelper
  
  	def index
    #@users = User.all
    	@post1 = HomeHelper::posts_order(1)
    	@post2 = HomeHelper::posts_order(2)
    	@post3 = HomeHelper::posts_order(3)
  	end
end

app/helpers/home_helper.rb
module HomeHelper
	# MOD KIMADA 5/1/2013
	def self.posts_order(which)
		@p = Post.where(['publish_date <= ?', Date.today]).order('publish_date DESC')
		@posto = @p[which - 1]
	end
end

app/views/home/index.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<!--
Design by Free CSS Templates
http://www.freecsstemplates.org
Released for free under a Creative Commons Attribution 2.5 License

Name       : News Beat
Description: A fixed-width design suitable for small sites and blogs.
Version    : 1.0
Released   : 20071215
-->
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<title>Women in Technology</title>
<meta name="keywords" content="" />
<meta name="description" content="" />
<!--added direct link to bootsrap.css instead of default style.css -spark 5/4/2013) -->
<link href="assets\bootstrap.css" rel="stylesheets" type="text/css" media="screen" />
</head>
<!--added missing body tag -spark 5/2/2013 -->
<body>
	<!--adding bootsrap.js to modify views -spark 5/4/2013-->
<script scr="js/bootstrap.js"></script>
<div id="latest-post" class="post">
	<!--<p class="byline"><span>Posted on April 21st, 2013 by <a href="#">Alison Ross</a></span></p>-->
	<h1 class="title"><a href="#">About This Site</a></h1>
	<div class="img.left"><img src="assets/mwit_logo.jpg" alt="" width="80" height="100" class="left" />
	<!--<div class="img.right"><img src="assets/mwit_logo.jpg" alt="" width="140" height="180" class="right" />-->
		<p>This site is moderated by the computer science department at Mills College, Oakland. Its purpose is to share information that is useful for women pursuing a career in technology. While primarily for the women at Mills, we hope that this resource will prove useful for all women seeking to make a mark in the business of computing.</p>

		<!-- <p>Information posted can be accessed by anyone, but you must sign up to comment or post.</p>-->
	 </div> 
	<!--<p class="meta"><a href="#" class="comments">14 Comments</a> &nbsp;&nbsp;&nbsp; <a href="#" class="permalink">Permalink</a></p>-->
	</div> 
	<div style="clear: both; height: 20px;">&nbsp;</div> <!-- this adds necssary  spacing-spark 5/4/2013-->
	<ul class="nav nav-list">
		<li class="divider"></li>
		<li class="divider"></li>
	</ul>
<div id="recent-posts" >
	<h2><%= link_to "Current Posts", posts_path %></h2> 
	<ul>
		<li class="first">
			<%# MOD KIMADA 5/1/2013 %>
			<% unless @post1.nil? %>
				<h3><%= @post1.title %></h3>
				<p><strong>[<%= @post1.publish_date %>]</strong> 
				<%= truncate(@post1.body, :length => 365) %>
				<%= link_to "More…", post_path(@post1) %></p>
			<% end %>
		</li>
		<li>
			<% unless @post2.nil? %>
				<h3><%= @post2.title %></h3>
				<p><strong>[<%= @post2.publish_date %>]</strong> 
				<%= truncate(@post2.body, :length => 365) %>
				<%= link_to "More…", post_path(@post2) %></p>
			<% end %>
		</li>
		<li>
			<% unless @post3.nil? %>
				<h3><%= @post3.title %></h3>
				<p><strong>[<%= @post3.publish_date %>]</strong> 
				<%= truncate(@post3.body, :length => 365) %>
				<%= link_to "More…", post_path(@post3) %></p>
			<% end %>
			<%# END MOD KIMADA %>
		</li>
	</ul>
	
	<div style="clear: both; height: 40px;">&nbsp;
	</div>  
</div> 
<ul class="nav nav-list">
		<li class="divider"></li>
	</ul>
<div id="sidebar">
	<ul>
		<li id="search">
			<h2>Search</h2>
			<!-- adding mod to form view like search placeholder and etc..-spark 5/4/2013-->
			<form class="well form-search" id="searchform" method="get" action="">
				<div>
					<input type="text" class="span3 search-query" placeholder="Search..." name="s" id="s" size="15" />
					<button class="btn"><i class="icon-search"></i> Search</button>
					<br />
					<!-- remvd and added bootstrap rounded with hint -spark 05/04/2013
					<input name="submit" type="submit" value="Search" />-->
				</div>
			</form>
		</li>
		<li id="calendar">
			<h2>Calendar</h2>
			<div id="calendar_wrap">
				<table summary="Calendar">
					<caption>
					May 2013
					</caption>
					<thead>
						<tr>
							<th abbr="Monday" scope="col" title="Monday">M</th>
							<th abbr="Tuesday" scope="col" title="Tuesday">T</th>
							<th abbr="Wednesday" scope="col" title="Wednesday">W</th>
							<th abbr="Thursday" scope="col" title="Thursday">T</th>
							<th abbr="Friday" scope="col" title="Friday">F</th>
							<th abbr="Saturday" scope="col" title="Saturday">S</th>
							<th abbr="Sunday" scope="col" title="Sunday">S</th>
						</tr>
					</thead>
					<tfoot>
						<tr>
							<td abbr="April" colspan="3" id="prev"><a href="#" title="View posts for April 2013">&laquo; Apr</a></td>
							<td class="pad">&nbsp;</td>
							<td abbr="June" colspan="3" id="next"><a href="#" title="View posts for June 2013">Jun &raquo;</a></td>
						</tr>
					</tfoot>
					<tbody>
						<tr>
							<td colspan="3" class="pad">&nbsp;</td>
							
							<td>1</td>
							<td>2</td>
							<td>3</td>
							<td>4</td>
						</tr>
						<tr>
							<td>5</td>
							<td>6</td>
							<td>7</td>
							<td>8</td>
							<td>9</td>
							<td>10</td>
							<td>11</td>
						</tr>
						<tr>
							<td><a href="#">12</a></td>
							<td>13</td>
							<td>14</td>
							<td>15</td>
							<td>16</td>
							<td>17</td>
							<td>18</td>
						</tr>
						<tr>
							<td>19</td>
							<td>20</td>
							<td>21</td>
							<td>22</td>
							<td>23</td>
							<td id="today">24</td>
							<td>25</td>
						</tr>
						<tr>
							<td>26</td>
							<td>27</td>
							<td>28</td>
							<td>29</td>
							<td>30</td>
							<td class="pad" colspan="2">&nbsp;</td>
						</tr>
					</tbody>
				</table>
			</div>
		</li>
		<li id="categories-1">
			<h2>Categories</h2>
			<ul>
				<li><a href="#" title="View all posts filed under Uncategorized">Uncategorized</a> </li>
				<li><a href="#" title="View all posts filed under Jobs">Jobs</a> </li>
				<li><a href="#" title="View all posts filed under Internships">Internships</a> </li>
				<li><a href="#" title="View all posts filed under Scholarships">Scholarships</a> </li>
				<li><a href="#" title="View all posts filed under Events">Events</a> </li>
			</ul>
		</li>
	</ul>

	<div style="clear: both; height: 40px;">&nbsp;</div>
</div>
<hr />
<div id="footer">
	<p class="legal">&copy;2013 All Rights Reserved.</p>
	<p class="credit">Designed by R-KATZ Project CS170 <a href="#" > R-KATZ</a>.</p>
</div>
</body>
</html>

app/views/home/testing.index.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<title>Women in Technology</title>
<meta name="keywords" content="" />
<meta name="description" content="" />
<!--added direct link to application.css instead of default style.css (spark) -->
<!-- adding href=bootstrap.css here-->
<link href="bootstrap.css" rel="stylesheets" type="text/css" media="screen" />
</head>
<body> <!-- added missing body tag-->
<script scr="js/bootstrap.js"></script>
<div id="latest-post" class="post">
	<!--<p class="byline"><span>Posted on April 21st, 2013 by <a href="#">Alison Ross</a></span></p>-->
	<h1 class="title"><a href="#">About This Site</a></h1>
	<div class="img.left"><img src="assets/mwit_logo.jpg" alt="" width="70" height="90" class="left" />
		<p>This site is moderated by the computer science department at Mills College, Oakland. Its purpose is to share information that is useful for women pursuing a career in technology. While primarily for the women at Mills, we hope that this resource will prove useful for all women seeking to make a mark in the business of computing.</p>
		<!-- 
		<p>Information posted can be accessed by anyone, but you must sign up to comment or post.</p>
		-->
		
	 </div>
	<!--<p class="meta"><a href="#" class="comments">14 Comments</a> &nbsp;&nbsp;&nbsp; <a href="#" class="permalink">Permalink</a></p>-->
	</div> 

	<!--adding bootstrap for html viewing pleasure -spark -->
<form class="well span6">
	<label>Username</label>
	<input type="text" class="span3" /><br/>
	<label>Password</label>
	<input type="text" class="span3" /><br/>
	<button class="btn btn-primary">Submit</button>
	<button class="btn">Clear</button></br>

</form>

<div id="recent-posts">
	<h2><%= link_to "Current Posts", posts_path %></h2>
	<ul>
		<li class="first">
			<%# MOD KIMADA 5/1/2013 %>
			<% unless @post1.nil? %>
				<h3><%= @post1.title %></h3>
				<p><strong>[<%= @post1.publish_date %>]</strong> 
				<%= truncate(@post1.body, :length => 365) %>
				<%= link_to "More…", post_path(@post1) %></p>
			<% end %>
		</li>
		<li>
			<% unless @post2.nil? %>
				<h3><%= @post2.title %></h3>
				<p><strong>[<%= @post2.publish_date %>]</strong> 
				<%= truncate(@post2.body, :length => 365) %>
				<%= link_to "More…", post_path(@post2) %></p>
			<% end %>
		</li>
		<li>
			<% unless @post3.nil? %>
				<h3><%= @post3.title %></h3>
				<p><strong>[<%= @post3.publish_date %>]</strong> 
				<%= truncate(@post3.body, :length => 365) %>
				<%= link_to "More…", post_path(@post3) %></p>
			<% end %>
			<%# END MOD KIMADA %>
		</li>
	</ul>
	
	<div style="clear: both; height: 40px;">&nbsp;</div>
</div>
<div id="sidebar">
	<ul>
		<li id="search">
			<h2>Search</h2>
			<form id="searchform" method="get" action="">
				<div>
					<input type="text" name="s" id="s" size="15" />
					<br />
					<input name="submit" type="submit" value="Search" />
				</div>
			</form>
		</li>
		<li id="calendar">
			<h2>Calendar</h2>
			<div id="calendar_wrap">
				<table summary="Calendar">
					<caption>
					May 2013
					</caption>
					<thead>
						<tr>
							<th abbr="Monday" scope="col" title="Monday">M</th>
							<th abbr="Tuesday" scope="col" title="Tuesday">T</th>
							<th abbr="Wednesday" scope="col" title="Wednesday">W</th>
							<th abbr="Thursday" scope="col" title="Thursday">T</th>
							<th abbr="Friday" scope="col" title="Friday">F</th>
							<th abbr="Saturday" scope="col" title="Saturday">S</th>
							<th abbr="Sunday" scope="col" title="Sunday">S</th>
						</tr>
					</thead>
					<tfoot>
						<tr>
							<td abbr="Aoril" colspan="3" id="prev"><a href="#" title="View posts for April 2013">&laquo; Apr</a></td>
							<td class="pad">&nbsp;</td>
							<td abbr="June" colspan="3" id="next"><a href="3" title="View posts for June 2013">Jun &raquo;</a></td>
						</tr>
					</tfoot>
					<tbody>
						<tr>
							<td colspan="3" class="pad">&nbsp;</td>
							
							<td>1</td>
							<td>2</td>
							<td>3</td>
							<td>4</td>
						</tr>
						<tr>
							<td>5</td>
							<td>6</td>
							<td>7</td>
							<td>8</td>
							<td>9</td>
							<td>10</td>
							<td>11</td>
						</tr>
						<tr>
							<td><a href="#">12</a></td>
							<td>13</td>
							<td>14</td>
							<td>15</td>
							<td>16</td>
							<td>17</td>
							<td>18</td>
						</tr>
						<tr>
							<td>19</td>
							<td>20</td>
							<td>21</td>
							<td>22</td>
							<td>23</td>
							<td id="today">24</td>
							<td>25</td>
						</tr>
						<tr>
							<td>26</td>
							<td>27</td>
							<td>28</td>
							<td>29</td>
							<td>30</td>
							<td class="pad" colspan="2">&nbsp;</td>
						</tr>
					</tbody>
				</table>
			</div>
		</li>
		<li id="categories-1">
			<h2>Categories</h2>
			<ul>
				<li><a href="#" title="View all posts filed under Uncategorized">Uncategorized</a> (3) </li>
				<li><a href="#" title="View all posts filed under Lorem Ipsum">Jobs</a> (42) </li>
				<li><a href="#" title="View all posts filed under Urna Congue Rutrum">Internships</a> (28) </li>
				<li><a href="#" title="View all posts filed under Augue Praesent">Scholarships</a> (55) </li>
				<li><a href="#" title="View all posts filed under Vivamus Fermentum">Events</a> (13) </li>
			</ul>
		</li>
	</ul>
	<div style="clear: both; height: 40px;">&nbsp;</div>
</div>
<hr />
<div id="footer">
	<p class="legal">&copy;2013 All Rights Reserved.</p>
	<p class="credit">Designed by <a href="http://www.freecsstemplates.org">FCT</a>.</p>
</div>
</body>
</html>