config/routes.rb
Mblog::Application.routes.draw do
  
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  resources :categories

  resources :posts do
  	resources :comments
  end
  
  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  #devise_for :users
  resources :users 

  #match 'auth/facebook/callback' => 'sessions#create',:as => 'login'
  #match 'auth/linkedin/callback' => 'sessions#create',:as => 'login'
  #match 'logout' => 'sessions#destroy'

end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<body>
<div id="header">
  <h1><%= link_to "Women in Technology", root_path %></h1>
  <h2> <a href="http://www.mills.edu" target = 'new' >Mills College</a> </h2>
</div>
<div id="menu"> 
  <ul>
    <li class="first"><%=link_to "Home", root_path%></li>
    <% if user_signed_in? %>
    <li>
    <%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %>
    </li>
  <% else %>
    <li>
    <%= link_to 'Login', new_user_session_path %>
    </li>
  <% end %>
    <% if user_signed_in? %>
    <li>
    <%= link_to 'Edit account', edit_user_registration_path %>
    </li>
    <!--added Posts link to menu for users/admin-spark 5/04/2013 -->
    <li>
      <%= link_to 'Posts', posts_path %>
      </li>
    <% if current_user.has_role? :admin %>
      <li>
      <%= link_to 'Users', users_path %>
      </li>
      <li>
      <%= link_to 'Categories', categories_path %>
      </li>
       
    <% end %>
  <% else %>
    <li>
    <%= link_to 'Sign up', new_user_registration_path %>
    </li>
  <% end %>
    <li><a href="http://www.linkedin.com/groups/Mills-College-Connections-46150?gid=46150&mostPopular=&trk=tyah" target = 'new' accesskey="4" title="Career Connections">Connections</a></li>
     <li><a href="http://www.mills.edu/admission/undergraduate/internships.php" target = 'new' accesskey="4" title="Internships">Internships</a></li>
  </ul>
</div>
<hr />

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Mills Women in Technology" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Mills Women in Technology" %>">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body class="<%= controller_name %> <%= action_name %>">
    <div class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </div>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <!--modifying column views -spark 5/4/2013 -->
            <div class="span12"><%= yield %>
              <div class="span3">
              <%= render 'layouts/messages' %>
            <div class="span3">
            </div>
          </div>
        </div>
      </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>